# aplication name
quarkus.application.name=produtos-mae

# PostgreSQL settings
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=root123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/produtos-mae

# Automatic update in data
quarkus.hibernate-orm.database.generation=update

# activate Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger
quarkus.hibernate-orm.log.sql=true