# Application Name
quarkus.application.name=produtos-mae

# PostgreSQL Settings (Configurável via .env ou Variáveis de Ambiente)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/produtos-mae}

# Automatic Database Generation Schema
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

# Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

# CORS Configuration
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=*
quarkus.http.cors.methods=*
quarkus.http.cors.access-control-allow-headers=*
quarkus.http.cors.access-control-allow-methods=*

# Quarkus Mailer Configuration (Configurável via .env ou Variáveis de Ambiente)
quarkus.mailer.auth-methods=PLAIN LOGIN
quarkus.mailer.from=${SMTP_FROM:suporte@naturanice.com}
quarkus.mailer.host=${SMTP_HOST:smtp.gmail.com}
quarkus.mailer.port=${SMTP_PORT:587}
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=${SMTP_USERNAME:exemplo@gmail.com}
quarkus.mailer.password=${SMTP_PASSWORD:sua_senha_de_app_16_digitos}
quarkus.mailer.mock=${SMTP_MOCK:false}